### ISSUE TITLE
Marks on U+11705 AHOM LETTER ALTERNATE TA are instead placed on the following U+1170A AHOM LETTER JA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/ahom#17]
### Font
NotoSerifAhom-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/ahom/releases/tag/NotoSerifAhom-v2.007
Date: 2023-09-27

### Font version
Version 2.007

### Issue
Marks are attached to the <i>ta</i>–<i>ja</i> ligature identically regardless of whether they follow the <i>ta</i> or the <i>ja</i>. If both are attested, they should look different. Alternatively, if the purpose of U+11705 AHOM LETTER ALTERNATE TA is only to ligate with <i>ja</i> and never have a mark of its own, then putting a mark after the <i>ta</i> is a typo, which shouldn’t be obscured by making it look identical to the correct spelling, so they should look different.

@StephenMorey, any input you have about U+11705 would be welcome.

### Character data
𑜅𑜤𑜊𑜅𑜊𑜤
U+11705 AHOM LETTER ALTERNATE TA
U+11724 AHOM VOWEL SIGN U
U+1170A AHOM LETTER JA
U+11705 AHOM LETTER ALTERNATE TA
U+1170A AHOM LETTER JA
U+11724 AHOM VOWEL SIGN U

### Screenshot
![𑜅𑜤𑜊𑜅𑜊𑜤](https://github.com/notofonts/ahom/assets/1124347/08fadd00-5057-4781-bdb8-f818c62f3215)

**Comment by StephenMorey** [comment]
Thank you for doing this work. U+11705 has comparatively few uses in the Ahom manuscripts. Its most significant use, which we probably should have included in the original Unicode proposal, is for the combination 'te yau', which is a sentence final series of 'particles' meaning something like 'it's truly so'. This is the combination of U+11705, U+1170A, then U+11726 (Ahom vowel E) and U+11727 (Ahom Vowel AW). There is an example of this in Figure 6 in the unicode proposal. (https://unicode.org/L2/L2012/12309-ahom-rev.pdf). I don't have any evidence for it's use in any other circumstance; but I do recall that Martin and I discussed this and felt that the alternate TA was the best way forward to achieve it.

**Comment by simoncozens** [comment]
OK; then I think this is a non-issue. I'm usually pretty completist about this sort of thing, but there are limits. :-)
