### ISSUE TITLE
Missing additional Ahom characters

### ISSUE THREAD

**Issue by EkiRahardian** [notofonts/ahom#6]
### Font 
  > NotoSerifAhom-Regular.ttf

### Where the font came from, and when
  >   Site: https://notofonts.github.io/fonts/NotoSerifAhom/full/ttf/NotoSerifAhom-Regular.ttf
  >   Date: 2022-07-04

### Font Version
  > v2.005

### Issue
  > As of Unicode version 14.0, 7 new characters were added to the Ahom Unicode block, these characters are not covered in Noto Serif Ahom per 04 July 2022.

### Character data
  > 11740 𑝀 AHOM LETTER CA
  > 11741 𑝁 AHOM LETTER TTA
  > 11742 𑝂 AHOM LETTER TTHA
  > 11743 𑝃 AHOM LETTER DDA
  > 11744 𑝄 AHOM LETTER DDHA
  > 11745 𑝅 AHOM LETTER NNA
  > 11746 𑝆 AHOM LETTER LLA

### Reference
  > http://unicode.org/charts/PDF/U11700.pdf

### Screenshot
  > ![image](https://user-images.githubusercontent.com/23203226/177088182-be0054ea-6a5f-42b7-98b4-f22bcfe57382.png)

**Comment by simoncozens** [comment]
@punchcutter has provided me with some sources of a modified Noto Serif Ahom which he used to create the Unicode codepoint charts, and I'm hoping to get these added into our sources.

However, @ohbendy had a question about

> LLA, which in the attestations has a dotted terminal on the left side, but is described as having a dot on the right side. I think Stephen just made a typo there, but the proposal font and Unicode chart follows the description instead of the shape presented.

Here's the code charts:

<img width="75" alt="Screenshot 2023-01-03 at 09 44 49" src="https://user-images.githubusercontent.com/106728/210333060-538e64c6-42b7-4b35-ad8f-fece9f8ec336.png">

and the description from L2/20-258:

> Retroflex ḷ, created by adding a black circle ‘dot’ to the *right hand end* of AHOM LETTER LA

The examples from the proposal:

<img width="179" alt="Screenshot 2023-01-03 at 09 49 37" src="https://user-images.githubusercontent.com/106728/210333807-52f5145e-0848-4fc2-a9c5-ebd70ceb9034.png"><img width="115" alt="Screenshot 2023-01-03 at 09 47 37" src="https://user-images.githubusercontent.com/106728/210333490-c3b4f528-b034-4ecc-be0a-66215acaa90b.png">

@StephenMorey, could you confirm whether new character LLA should have a black dot on the right side or the left side? (Or both...)

**Comment by StephenMorey** [comment]
Tai Ahom LLA should have the black dot on both sides. The existing LA 11746 has the black dot / circle only on the right hand side, but the LLA should have an additional black circle dot on the left hand side, as well has the existing dot on the right hand side. I apologize for writing this incorrectly. LLA needs dots on both sides!
